// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMUIZZaxGSLfRPYklo3x9luZ5DgA2HfU0',
    appId: '1:263342103052:android:c8b181b07e6b88d0946c29',
    messagingSenderId: '263342103052',
    projectId: 'ai-story-book-22d4e',
    storageBucket: 'ai-story-book-22d4e.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOugigNCVbP4OGz3cO_W5HQ7Lo_QxQQOw',
    appId: '1:263342103052:web:13bc4b5e1e681d35946c29',
    messagingSenderId: '263342103052',
    projectId: 'ai-story-book-22d4e',
    authDomain: 'ai-story-book-22d4e.firebaseapp.com',
    storageBucket: 'ai-story-book-22d4e.firebasestorage.app',
    measurementId: 'G-D08ZT873QV',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMUIZZaxGSLfRPYklo3x9luZ5DgA2HfU0',
    appId: '1:263342103052:windows:a119b3af04c9ee65946c29',
    messagingSenderId: '263342103052',
    projectId: 'ai-story-book-22d4e',
    storageBucket: 'ai-story-book-22d4e.firebasestorage.app',
  );
}
